"""Persona ontology.

The structure here echoes SDG-PGMs' separation of *variable declarations*
(``get_variables``), *graph edges* (``get_edges``), and *generated samples*.
We declare the variables here as :class:`PersonaDimension` and let the
generator read them; the generator owns the actual probability tables.

A :class:`Persona` is one synthetic Vietnamese individual. Categorical
fields are stored both in their **canonical Vietnamese form** (matching
the labels NSO publishes in the PX-Web statistical database) and in a
parallel English form, so downstream tools can switch language without
re-mapping. Same for the bio: ``bio_vi`` is the original Vietnamese
narrative, ``bio_en`` is the parallel English translation.

A :class:`PersonaBatch` is a typed wrapper around a list of personas plus
generation metadata (seed, scrape snapshot, LLM enrichment status) so
personas remain reproducible and auditable.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class PersonaDimension(BaseModel):
    """One axis along which a persona is described.

    Loaded from ``configs/ontology.yaml`` (the ``persona_dimensions`` list).
    The ``parents`` field encodes the directed edges of the cascaded
    Bayesian-style network — the sampler walks dimensions in topological
    order, conditioning each one on its parents' already-sampled values.
    The ``sources`` field is the provenance trail: every PX-Web table id
    (``V02.41``, ``V02.43``, ...) whose distribution feeds this
    dimension's CPD. Empty when the dimension is grounded in a
    non-PX-Web prior.
    """

    model_config = ConfigDict(extra="forbid")

    id: str
    domain: str = Field(description="Statistical domain id, e.g. 'population'")
    parents: list[str] = Field(default_factory=list)
    cardinality: int = Field(gt=0)
    sources: list[str] = Field(default_factory=list,
                                 description="PX-Web matrix ids that feed this dimension's CPD")


class Persona(BaseModel):
    """One synthetic Vietnamese persona, bilingual.

    Each categorical field has a ``_vi`` (the NSO-published Vietnamese
    label) and an ``_en`` mirror. ``age`` is numeric and language-neutral.
    ``bio_vi`` and ``bio_en`` are the narrative fields; for vanilla
    template-generated personas they are mechanical translations of the
    structured columns. The ``personas-vn enrich-personas`` LLM pass
    overwrites both with a richer paragraph.
    """

    model_config = ConfigDict(extra="forbid")

    persona_id: str
    name: str

    # Geography (region label is the canonical NSO macro-region name)
    region: str           # Vietnamese (canonical NSO label)
    region_en: str
    urbanicity: str       # "Thành thị" / "Nông thôn"
    urbanicity_en: str    # "urban" / "rural"

    # Demographics
    age_group: str
    age: int
    sex: str              # "Nam" / "Nữ"
    sex_en: str           # "male" / "female"
    ethnicity: str        # Vietnamese
    ethnicity_en: str
    marital_status: str
    marital_status_en: str

    # Socio-economic
    education_level: str
    education_level_en: str
    employment_status: str
    employment_status_en: str
    occupation: str
    occupation_en: str
    industry_sector: str
    industry_sector_en: str
    income_quintile: str
    income_quintile_en: str

    # Narrative + provenance
    bio_vi: str | None = None
    bio_en: str | None = None
    enriched: bool = Field(
        default=False,
        description="True if bio_vi/bio_en were generated by the LLM enrichment pass",
    )
    sources: list[str] = Field(
        default_factory=list,
        description="PX-Web table ids the distributions were grounded in",
    )


class PersonaBatch(BaseModel):
    """A reproducible set of personas plus generation metadata."""

    model_config = ConfigDict(extra="forbid")

    generated_at: datetime
    n: int
    seed: int
    ontology_version: str
    scrape_manifest: dict[str, Any] = Field(default_factory=dict)
    enrichment: dict[str, Any] = Field(
        default_factory=dict,
        description="If LLM enrichment ran: model name, n_enriched, started_at, base_url",
    )
    personas: list[Persona] = Field(default_factory=list)

    def to_records(self) -> list[dict[str, Any]]:
        """Flatten to plain dicts (handy for ``pandas.DataFrame.from_records``)."""
        return [p.model_dump() for p in self.personas]
