"""Re-render every UMAP / embedding figure in DATASYNTHESIS.ipynb +
DATAEXPLORATION.ipynb with the standardised canvas, margins, and
multi-line legend treatment.

Why this exists separately from the notebook builders:
    `scripts._build_datasynthesis_nb` / `scripts._build_dataexploration_nb`
build the **notebook source** — they emit a fresh ``DATA*.ipynb`` whose
cells contain the new styling code, but they don't actually execute the
cells. The figures the markdown documents embed live as PNG / HTML files
under ``docs/figures/synthesis/`` and ``docs/figures/exploration/`` and
can only be regenerated by running the cells against real data. The
slowest cells (sentence-transformers embedding + UMAP) take ~10 min on
CPU and we don't want to pay that cost just to restyle the 9 scatter
plots — the cached parquets they wrote (``reduced.parquet`` and friends)
already carry every input the figures need.

This script reads those cached parquets directly and re-renders the 9
embedding figures (4 from DATASYNTHESIS — figs 02-05; 5 from
DATAEXPLORATION — figs 06, 07, 08, 09, 11) with the same standardised
``EMBED_FIG_W`` × ``EMBED_FIG_H`` canvas, ``EMBED_MARGIN_*`` margins,
and ``_wrap``-driven multi-line legend that the notebook builders now
emit. Outputs land in the same ``docs/figures/{synthesis,exploration}/``
locations the notebooks use, so ``DATA*.md`` keeps rendering correctly
without any re-execution.

Run::

    python -m scripts._rerender_embedding_figures
"""

from __future__ import annotations

import json
import sys
import warnings
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

warnings.filterwarnings("ignore")

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts._nvidia_style import (  # noqa: E402
    NV_BLACK,
    NV_DARK,
    NV_DISCRETE,
    NV_FONT_FAMILY,
    NV_GREEN,
    NV_GREEN_DARK,
    NV_GREEN_SOFT,
    NV_GREY,
    NV_LIGHT_GREY,
    NV_SEQUENTIAL,
    apply_nvidia_style,
    save_figure,
)


# ---------------------------------------------------------------------------
# Standardised dimensions (kept in lockstep with the notebook builders)
# ---------------------------------------------------------------------------
EMBED_FIG_W = 1100
EMBED_FIG_H = 720
# Categorical layout reserves a 240-px right-side strip for the legend
# (mirrors the colorbar-right convention of the continuous figures);
# wrapped 30-char labels stack in a single tidy column.
EMBED_MARGIN_CATEGORICAL = dict(l=80, r=240, t=80, b=80)
EMBED_MARGIN_CONTINUOUS = dict(l=80, r=140, t=80, b=80)
WRAP_AT = 30


def _wrap(label, max_chars: int = WRAP_AT) -> str:
    """Word-aware <br> insertion so a long category label wraps onto
    multiple legend lines without ever splitting a token."""
    if not isinstance(label, str) or len(label) <= max_chars:
        return str(label)
    out, cur = [], ""
    for w in label.split():
        if cur and len(cur) + 1 + len(w) > max_chars:
            out.append(cur)
            cur = w
        else:
            cur = (cur + " " + w).strip()
    if cur:
        out.append(cur)
    return "<br>".join(out)


EMBED_LEGEND_RIGHT = dict(
    title="",
    orientation="v",
    yanchor="top",
    y=1,
    xanchor="left",
    x=1.02,
    font=dict(size=11),
    tracegroupgap=4,
    itemsizing="constant",
)


# ---------------------------------------------------------------------------
# Plotly default theme — match the notebooks
# ---------------------------------------------------------------------------
pio.templates["nvidia"] = go.layout.Template(
    layout=go.Layout(
        paper_bgcolor="white",
        plot_bgcolor="white",
        font=dict(family=NV_FONT_FAMILY, color=NV_BLACK, size=13),
        colorway=NV_DISCRETE,
    )
)
pio.templates.default = "nvidia"


# ---------------------------------------------------------------------------
# Output directories
# ---------------------------------------------------------------------------
SYNTH_OUT = REPO_ROOT / "docs" / "figures" / "synthesis"
EXPL_OUT = REPO_ROOT / "docs" / "figures" / "exploration"
SYNTH_OUT.mkdir(parents=True, exist_ok=True)
EXPL_OUT.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# DATASYNTHESIS — fig 02..05 from data/Nemotron-Personas-Vietnam/_subset_pipeline
# ---------------------------------------------------------------------------
def render_datasynthesis() -> None:
    subset_dir = REPO_ROOT / "data" / "Nemotron-Personas-Vietnam" / "_subset_pipeline"
    reduced_path = subset_dir / "reduced.parquet"
    if not reduced_path.exists():
        print(f"  SKIP DATASYNTHESIS — {reduced_path} missing; run DATASYNTHESIS.ipynb first")
        return

    reduced = pd.read_parquet(reduced_path)
    plot_sample = min(6000, len(reduced))

    def _scatter(color_col: str, title: str) -> go.Figure:
        df_plot = reduced.sample(plot_sample, random_state=20260506).copy()
        df_plot["_legend"] = df_plot[color_col].map(_wrap)
        legend_order = sorted(df_plot["_legend"].unique())
        fig = px.scatter(
            df_plot,
            x="x",
            y="y",
            color="_legend",
            title=title,
            opacity=0.7,
            color_discrete_sequence=NV_DISCRETE,
            category_orders={"_legend": legend_order},
            hover_data={
                "occupation": True,
                "region": True,
                "education_level": True,
                "_legend": False,
                "x": False,
                "y": False,
            },
        )
        fig.update_traces(marker=dict(size=4, line=dict(width=0)))
        fig.update_xaxes(title="UMAP-x")
        fig.update_yaxes(title="UMAP-y")
        apply_nvidia_style(fig)
        fig.update_layout(
            width=EMBED_FIG_W,
            height=EMBED_FIG_H,
            margin=EMBED_MARGIN_CATEGORICAL,
            legend=EMBED_LEGEND_RIGHT,
        )
        return fig

    targets = [
        ("region", "UMAP — coloured by macro-region", "02_umap_by_region"),
        (
            "occupation",
            "UMAP — coloured by occupation (10-class ISCO)",
            "03_umap_by_occupation",
        ),
        (
            "education_level",
            "UMAP — coloured by education level",
            "04_umap_by_education",
        ),
        (
            "area",
            "UMAP — coloured by area (urban / rural)",
            "05_umap_by_area",
        ),
    ]
    for col, title, name in targets:
        fig = _scatter(col, title)
        png, html = save_figure(
            fig,
            name,
            width=EMBED_FIG_W,
            height=EMBED_FIG_H,
            out_dir=SYNTH_OUT,
        )
        print(f"  wrote {png.relative_to(REPO_ROOT) if png else '(no png)'}")


# ---------------------------------------------------------------------------
# DATAEXPLORATION — fig 06, 07, 08, 09, 11 from data/nso-gov-vn/...
# ---------------------------------------------------------------------------
DOMAIN_VI_EN = {
    "population": "Dân số và lao động / Population & labour",
    "national_accounts": "Tài khoản quốc gia / National accounts",
    "investment": "Đầu tư / Investment",
    "enterprises": "Doanh nghiệp / Enterprises",
    "agriculture": "Nông lâm thủy sản / Agriculture",
    "industry": "Công nghiệp / Industry",
    "trade": "Thương mại, giá cả / Trade & prices",
    "transport": "Vận tải, bưu điện / Transport",
    "education": "Giáo dục / Education",
    "health": "Y tế, văn hóa / Health & society",
    "international": "Thống kê quốc tế / International stats",
    "geography": "Đơn vị HC, đất, khí hậu / Geography",
    "other": "Khác / Other",
}


def render_dataexploration() -> None:
    curator_dir = REPO_ROOT / "data" / "nso-gov-vn"
    extracted_path = curator_dir / "extracted" / "extracted.jsonl"
    embedded_path = curator_dir / "embedded" / "embedded.parquet"
    reduced_path = curator_dir / "reduced" / "reduced.parquet"
    for p in (extracted_path, embedded_path, reduced_path):
        if not p.exists():
            print(f"  SKIP DATAEXPLORATION — {p} missing; run DATAEXPLORATION.ipynb first")
            return

    extracted = pd.read_json(extracted_path, lines=True)
    embedded = pd.read_parquet(embedded_path)
    reduced = pd.read_parquet(reduced_path)

    # Mirrors §6 — sc = reduced ⨝ extracted on id, with helper fields.
    sc = reduced.merge(
        extracted[["id", "database", "n_cells", "year_min", "year_max", "keywords"]],
        on="id",
        how="left",
    )
    sc["domain_id"] = sc["domain_id"].fillna("other")
    sc["kw_str"] = sc["keywords"].apply(
        lambda kw: ", ".join(kw[:5]) if isinstance(kw, list) else ""
    )

    DOMAIN_PALETTE = [
        NV_GREEN,
        NV_GREEN_DARK,
        NV_GREEN_SOFT,
        NV_BLACK,
        NV_GREY,
        "#3F6F00",
        "#94BD51",
        "#AED581",
        "#5C9300",
        NV_DARK,
        "#888888",
        "#444444",
    ]

    # ------- fig06 — UMAP × statistical domain -------
    fig06 = go.Figure()
    domain_order = sc["domain_id"].value_counts().index.tolist()
    for dom, color in zip(domain_order, DOMAIN_PALETTE):
        sub = sc[sc["domain_id"] == dom]
        fig06.add_trace(
            go.Scatter(
                x=sub["x"],
                y=sub["y"],
                mode="markers",
                name=_wrap(DOMAIN_VI_EN.get(dom, dom)),
                marker=dict(
                    size=8,
                    color=color,
                    line=dict(color=NV_BLACK, width=0.4),
                    opacity=0.85,
                ),
                customdata=np.column_stack(
                    [
                        sub["title"].fillna(""),
                        sub["database"].fillna(""),
                        sub["n_cells"].fillna(0).astype(int),
                        sub["kw_str"].fillna(""),
                    ]
                ),
                hovertemplate=(
                    "<b>%{customdata[0]}</b><br>"
                    "database: %{customdata[1]}<br>"
                    "cells: %{customdata[2]:,}<br>"
                    "keywords: %{customdata[3]}<extra></extra>"
                ),
            )
        )
    fig06.update_layout(
        title="UMAP — 502 bảng PX-Web tô màu theo lĩnh vực / "
        "UMAP — 502 PX-Web tables coloured by ontology domain",
        xaxis_title="UMAP-1",
        yaxis_title="UMAP-2",
    )
    apply_nvidia_style(fig06)
    fig06.update_layout(
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        margin=EMBED_MARGIN_CATEGORICAL,
        legend=EMBED_LEGEND_RIGHT,
    )
    save_figure(
        fig06,
        "06_umap_by_domain",
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        out_dir=EXPL_OUT,
    )
    print("  wrote docs/figures/exploration/06_umap_by_domain.png")

    # ------- fig07 — UMAP × NSO database (raw data column, not cluster) -------
    fig07 = go.Figure()
    DB_PALETTE = DOMAIN_PALETTE  # same 12-colour palette
    db_order = sc["database"].fillna("(unknown)").value_counts().index.tolist()
    for db, color in zip(db_order, DB_PALETTE):
        sub = sc[sc["database"].fillna("(unknown)") == db]
        fig07.add_trace(
            go.Scatter(
                x=sub["x"],
                y=sub["y"],
                mode="markers",
                name=_wrap(str(db)),
                marker=dict(
                    size=8,
                    color=color,
                    line=dict(color=NV_BLACK, width=0.4),
                    opacity=0.85,
                ),
                customdata=np.column_stack(
                    [
                        sub["title"].fillna(""),
                        sub["domain_id"].fillna(""),
                        sub["kw_str"].fillna(""),
                    ]
                ),
                hovertemplate=(
                    "<b>%{customdata[0]}</b><br>"
                    "domain: %{customdata[1]}<br>"
                    "keywords: %{customdata[2]}<extra></extra>"
                ),
            )
        )
    fig07.update_layout(
        title="UMAP — 502 bảng PX-Web tô màu theo cơ sở dữ liệu NSO / "
        "UMAP — 502 PX-Web tables coloured by NSO database",
        xaxis_title="UMAP-1",
        yaxis_title="UMAP-2",
    )
    apply_nvidia_style(fig07)
    fig07.update_layout(
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        margin=EMBED_MARGIN_CATEGORICAL,
        legend=EMBED_LEGEND_RIGHT,
    )
    save_figure(
        fig07,
        "07_umap_by_database",
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        out_dir=EXPL_OUT,
    )
    print("  wrote docs/figures/exploration/07_umap_by_database.png")

    # ------- fig08 — UMAP × cell count (continuous) -------
    sc["log_n"] = np.log10(sc["n_cells"].fillna(1).clip(lower=1))
    fig08 = go.Figure(
        go.Scatter(
            x=sc["x"],
            y=sc["y"],
            mode="markers",
            marker=dict(
                size=8,
                color=sc["log_n"],
                colorscale=NV_SEQUENTIAL,
                line=dict(color=NV_BLACK, width=0.4),
                opacity=0.9,
                showscale=True,
                colorbar=dict(
                    title=dict(
                        text="log₁₀(cells)",
                        font=dict(family=NV_FONT_FAMILY, color=NV_BLACK, size=12),
                    ),
                    tickvals=[0, 1, 2, 3, 4],
                    ticktext=["1", "10", "100", "1k", "10k"],
                ),
            ),
            customdata=np.column_stack(
                [
                    sc["title"].fillna(""),
                    sc["domain_id"].fillna(""),
                    sc["n_cells"].fillna(0).astype(int),
                ]
            ),
            hovertemplate=(
                "<b>%{customdata[0]}</b><br>"
                "domain: %{customdata[1]}<br>"
                "cells: %{customdata[2]:,}<extra></extra>"
            ),
        )
    )
    fig08.update_layout(
        title="UMAP × kích thước bảng / UMAP × table size (log₁₀ cells)",
        xaxis_title="UMAP-1",
        yaxis_title="UMAP-2",
        showlegend=False,
    )
    apply_nvidia_style(fig08)
    fig08.update_layout(
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        margin=EMBED_MARGIN_CONTINUOUS,
    )
    save_figure(
        fig08,
        "08_umap_by_cellcount",
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        out_dir=EXPL_OUT,
    )
    print("  wrote docs/figures/exploration/08_umap_by_cellcount.png")

    # ------- fig09 — UMAP × recency (continuous + small categorical) -------
    ymax = sc["year_max"].fillna(0)
    no_year = ymax == 0
    fig09 = go.Figure()
    sub = sc[no_year]
    fig09.add_trace(
        go.Scatter(
            x=sub["x"],
            y=sub["y"],
            mode="markers",
            name="no year info",
            marker=dict(
                size=7,
                color=NV_LIGHT_GREY,
                line=dict(color=NV_GREY, width=0.4),
                opacity=0.7,
            ),
            hovertemplate="<b>%{customdata[0]}</b><br>(no year info)<extra></extra>",
            customdata=np.column_stack([sub["title"].fillna("")]),
        )
    )
    sub = sc[~no_year]
    fig09.add_trace(
        go.Scatter(
            x=sub["x"],
            y=sub["y"],
            mode="markers",
            name="by year_max",
            marker=dict(
                size=8,
                color=sub["year_max"],
                colorscale=NV_SEQUENTIAL,
                cmin=2010,
                cmax=2024,
                line=dict(color=NV_BLACK, width=0.4),
                opacity=0.9,
                showscale=True,
                colorbar=dict(
                    title=dict(
                        text="year_max",
                        font=dict(family=NV_FONT_FAMILY, color=NV_BLACK, size=12),
                    ),
                ),
            ),
            customdata=np.column_stack(
                [
                    sub["title"].fillna(""),
                    sub["year_min"].fillna(0).astype(int),
                    sub["year_max"].fillna(0).astype(int),
                ]
            ),
            hovertemplate=(
                "<b>%{customdata[0]}</b><br>"
                "%{customdata[1]} – %{customdata[2]}<extra></extra>"
            ),
        )
    )
    fig09.update_layout(
        title="UMAP × năm cập nhật mới nhất / UMAP × most-recent year",
        xaxis_title="UMAP-1",
        yaxis_title="UMAP-2",
    )
    apply_nvidia_style(fig09)
    fig09.update_layout(
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        margin=EMBED_MARGIN_CONTINUOUS,
        legend=dict(
            title="",
            orientation="h",
            yanchor="top",
            y=1.02,
            xanchor="left",
            x=0.0,
            font=dict(size=11),
            itemsizing="constant",
            bgcolor="rgba(255,255,255,0.85)",
        ),
    )
    save_figure(
        fig09,
        "09_umap_by_recency",
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        out_dir=EXPL_OUT,
    )
    print("  wrote docs/figures/exploration/09_umap_by_recency.png")

    # ------- fig11 — semantic neighbours -------
    emb_df = embedded.merge(
        extracted[["id", "database"]], on="id", how="left"
    )
    V = np.stack(emb_df["vector"].to_list())
    S = V @ V.T

    fig11 = go.Figure()
    fig11.add_trace(
        go.Scatter(
            x=sc["x"],
            y=sc["y"],
            mode="markers",
            name="all 502 tables",
            marker=dict(size=5, color=NV_LIGHT_GREY, opacity=0.5),
            hoverinfo="skip",
            showlegend=True,
        )
    )
    ANCHOR_TABLE_IDS = ["V02.01", "V03.01", "V07.01", "V14.45"]
    ANCHOR_PALETTE = [NV_GREEN, NV_GREEN_DARK, NV_BLACK, NV_DARK]
    for anchor_id, color in zip(ANCHOR_TABLE_IDS, ANCHOR_PALETTE):
        rows = emb_df[emb_df["id"].str.endswith(":" + anchor_id)]
        if rows.empty:
            continue
        i = rows.index[0]
        sim = S[i].copy()
        sim[i] = -np.inf
        top = np.argsort(sim)[::-1][:5]
        indices = [i] + list(top)
        sub = sc[sc["id"].isin(emb_df.loc[indices, "id"])]
        is_anchor = sub["id"] == emb_df.loc[i, "id"]
        fig11.add_trace(
            go.Scatter(
                x=sub["x"],
                y=sub["y"],
                mode="markers+text",
                name=f"{anchor_id} + 5 neighbours",
                text=[anchor_id if a else "" for a in is_anchor],
                textposition="top center",
                textfont=dict(color=NV_BLACK, size=12),
                marker=dict(
                    size=[14 if a else 9 for a in is_anchor],
                    color=color,
                    line=dict(color=NV_BLACK, width=1.0),
                    symbol=["star" if a else "circle" for a in is_anchor],
                ),
                customdata=np.column_stack(
                    [sub["title"].fillna(""), sub["domain_id"].fillna("")]
                ),
                hovertemplate="<b>%{customdata[0]}</b><br>%{customdata[1]}<extra></extra>",
            )
        )
    fig11.update_layout(
        title="Bốn cụm láng giềng ngữ nghĩa trên UMAP / "
        "Four semantic neighbour groups projected onto UMAP",
        xaxis_title="UMAP-1",
        yaxis_title="UMAP-2",
    )
    apply_nvidia_style(fig11)
    fig11.update_layout(
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        margin=EMBED_MARGIN_CATEGORICAL,
        legend=EMBED_LEGEND_RIGHT,
    )
    save_figure(
        fig11,
        "11_semantic_neighbours",
        width=EMBED_FIG_W,
        height=EMBED_FIG_H,
        out_dir=EXPL_OUT,
    )
    print("  wrote docs/figures/exploration/11_semantic_neighbours.png")


def main() -> None:
    print("DATASYNTHESIS — re-rendering figs 02..05 to docs/figures/synthesis/ ...")
    render_datasynthesis()
    print()
    print("DATAEXPLORATION — re-rendering figs 06..09, 11 to docs/figures/exploration/ ...")
    render_dataexploration()
    print()
    print("done.")


if __name__ == "__main__":
    main()
